/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyTestProg;

public class App {
    public static void main(String[] args) {
        CommandFactory commandFactory = new CommandFactory();
        commandFactory.consoleMenu();
    }
}
